---
title: "Workout Cheatsheet"
description: |
  死虫、提踵动作要点
date: 2023-08-22
# date-modified: last-modified
#bibliography: references.bib
category: "Asana"
draft: false
---

## 卧姿动作

### 动作1 静态死虫

1.  先自然平躺，脚尖向前，屈膝，夹球，膝盖尽量靠近胸
2.  在保证腰始终压住地面的情况下，缓慢使大腿与地面垂直，小腿与地面平行，钩脚尖
3.  双手手心向内，伸直与地面垂直，肩胛骨稍往上提，背部胸腔打开
4.  吸气到背部胸腔处，呼气用内收肌夹小球
5.  保持至内收肌酸痛感（2min左右）

### 动作2 动态死虫

1.  先保持静态死虫姿势
2.  腰部放毛巾 感受腰部往下死劲压的感觉，吸气
3.  呼气，大腿根部蹬伸出去，保持住腰部往下压
4.  蹬伸至腰部快有空隙时，吸气，再呼气收回双腿
5.  至力竭

### 动作3 骨盆卷动

1.  自然平躺，屈膝保持脚尖向前，拇指球轻轻压住地面，夹小球
2.  双手掌心朝下，自然放在身体两侧
3.  吸气，呼气时收肚子，骨盆回卷，向上发力带动腰椎，胸椎脱离地面
4.  至最高处后慢慢下落，先放胸椎，再放腰椎，最后是屁股
5.  重复10个

臀桥动作注意点：

1.  观察脚尖是否向前
2.  拇指球始终压住地面
3.  臀部发力

动作1-3为一组，可做完一组休息，共三组

###  动作4 卷腹

#### 卷腹动作 版本1

1.  自然平躺，双腿自然抬起并屈膝，大腿与地面垂直，小腿与地面平行，双手向前伸，掌心向内
2.  吸气，呼气同时腹部发力，带动腰和胸远离地面，使手延伸至膝盖内侧
3.  吸气有控制的慢慢放回
4.  呼气重复步骤2-3，至力竭

#### 卷腹动作 版本2

1.  自然平躺在瑜伽垫上，双脚自然打开踩住地面
2.  双手抓住瑜伽垫的两角，吸气，呼气手臂和腹部用力，背部贴住瑜伽垫，使身体向上
3.  吸气缓缓下落
4.  呼气重复动作2-3，至力竭

#### 卷腹动作 版本3

1.  自然平躺，屈膝，双手抱住大腿后侧
2.  吸气，呼气的同时手臂和腹部用力，使腰尽力远离地面
3.  吸气慢慢有控制放回
4.  呼气重复步骤2-3，至力竭

卷腹动作注意点：注意力集中在腹部，尽量避免颈部发力

## 站姿动作

###  动作5 单腿提踵

1.  靠墙20cm站立，双腿自然打开，脚尖向前，双脚平行，拇指球压紧地面，脚趾头自然放松，双手微微扶墙
2.  双腿伸直，一只脚抬起远离地面
3.  吸气，呼气，拇指球用力，向上提踵至最高处
4.  吸气，再有控制地放下，并在压住拇指球的情况下 保证脚跟外侧先着地
5.  脚跟快接触地面时，呼气继续提踵，重复步骤3-4
6.  单侧提踵20次 换脚
7.  提踵3组后拉伸小腿，1min左右，有拉伸感即可

站姿提踵动作注意点：

1.  脚尖向前，脚伸直
2.  下落时保证拇指球踩稳地面，脚趾放松
3.  落地时脚跟外侧先靠近地面，但不要画圈
4.  收下巴

### 动作6 站姿髋外旋保持

1.  双腿打开，自然站立，保持脚尖向前，拇指球压住，脚跟压住
2.  骨盆回卷，收小腹，
3.  重心放在脚跟外侧，膝盖外旋，带动臀部收紧
4.  拉伸：大小腿呈90度，对侧肩膀往膝盖靠，感受屁股拉伸感
