project:
  type: website
  output-dir: docs

website:
  title: "Lin Yu"
  favicon: logos/favicon.png 
  page-navigation: true
  back-to-top-navigation: true
  #page-navigation: true
  navbar:
    title: false # override printing your website `title` (e.g. "Sam Csik" on line 6) in the top left corner of your navbar
    # logo: logos/favicon.png
    right:
      # - about.qmd
      - DLSPH.qmd
      - posts.qmd
      - href: index.qmd
        text: Home

  page-footer:
    background: light # or `dark`
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}


# format:
#   html:
#     theme: styles.scss
#     mainfont: Nunito
#     #css: styles.scss
#     toc: true
#     page-layout: article
    
format:
  html:
    resources: dis-lazyload.js
    page-layout: full
    sidebar: true
    theme:
      light: styles.scss
    #  dark: styles.scss
    # theme:
    #   light: default
    #   dark: default
      #- styles.scss
    mainfont: Josefin Sans
    toc: true
  

editor: source
