---
title: "hammeron"
---


A A D A( all 4 strums); 

Don't worry about a thing
'Cause every little thing gonna be alright
Singin', "Don't worry about a thing
'Cause every little thing gonna be alright"

A E A D; A; A E D A ( base + du + x + d for two times at each chord)
Rise up this mornin', smile with the risin' sun
Three little birds pitched by my doorstep
Singin' sweet songs of melodies pure and true
Sayin', "This is my message to you"


Singin', "Don't worry about a thing
'Cause every little thing is gonna be alright"
Singin', "Don't worry, don't worry 'bout a thing
'Cause every little thing's gonna be alright"


Rise up this mornin', smile with the risin' sun
Three little birds pitched by my doorstep
Singin' sweet songs of melodies pure and true
Sayin', "This is my message to you"


Singin', "Don't worry about a thing" (worry 'bout a thing, no)
"Every little thing gonna be alright" (don't worry)
Singin', "Don't worry about a thing (I won't worry)
'Cause every little thing gonna be alright"
Hmm, don't worry about a thing
'Cause a every little thing, gonna be alright (I won't worry)
Baby, don't worry about a thing
'Cause every little thing is gonna be alright
