---
title: "2024"
description: ""
tags: 
  - "annual"
---
## 二月

1. 泡腾片在水里的噗嗤声真的好治愈呀
2. 酱油炸鸡怎么能这么好吃韩国人是会做炸鸡的！
3. 竟然在楼下超市买到了超甜布林
4. 天呐世界上怎么有这么好吃的可颂呀 真的太好吃了吧
5. 金酒是好喝的 可酌情少饮
6. 网球老师真的是很凶 但讲得还是有一点点道理的但也不多
7. 怎么有这么好吃的李子呀
8. 我竟然发现学校旁边有银记
9. 天呐青提吃出了藿香正气水的味道
10. 世界上怎么有这么优秀的葡萄柚 谢谢你葡萄柚！
11. 天呐gala苹果怎么这么优秀
12. 小米粥谢谢你 离了你我怎么办呀
13. 开心果拿铁好喝但不能多喝
14. 感谢你路上的疯子你只是疯了一点但你并没有攻击性
15. 今天阳光很好 晒背开始这一天
16. 一年一度的present拜拜明年见🐸
17. 哦我的天呐怎么有这么傲娇的老板只收现金那他家的照烧鸡饭得多好吃呀！
18. 阿菊小天使又允许我掉一滴珍珠眼泪水！
19. 谢谢你congeeQueen 你真的太好吃了
20. 湖南小炒肉谢谢你 让我干了好几碗米饭
21. 谢谢你shawaema 你怎么可以这么咸 但我还会再给你一次机会！
22. 谢谢你大米饭 
23. 冰激凌真好吃 但可以不要那么甜
24. 披萨呀披萨你怎么知道一个又有韧劲又特别干脆的呢
25. salmon是好吃的 但是选择在一个冷天吃冷食有点子冷
26. 天呐谢谢你牛奶 你和可颂真是绝配
27. 谢谢你押尾老师没有您的音乐我是完不成作业的
28. 谢谢你亲爱的亮哥你人没了但你又没完全没
29. 谢谢你小裙子穿着你工作让我神采奕奕！
30. 谢谢你们小汤圆and小兔子 但我要暂时把你们收起来了 我永远爱你们 
31. 谢谢你巧巧哥你认真生活的样子也给我了很多力量
32. 谢谢小何 我当然会听你的话开心放轻松多运动多吃东西

## 三月
1. 叫我水果大王 天呐感谢你们水果可爱们 好好吃的水果
2. 双喜橙很好吃没吃出和脐橙有啥区别长得倒还真不一样
3. 健身房让我好精神棒棒哒但真是一点核心都没有
4. 天呐我好像是会放松我的手手了当我击球的时候 然后serve的grip和正手是不一样的所以感觉需要一些时间适应 且serve正手准备的要再快一些和左手同步天我很啰嗦
5. 哦我的天一种以为自己没带耳机但又在包里摸到耳机的快乐 谢谢你耳机
6. 韩国人的炸鸡和冷面好好吃呀 就是有点上火吧
7. 我还以为我没有带耳机，结果我发现我带了耳机开心
8. 今天-1度，但是游泳一点都不冷感觉非常的放松
9. 天呐这个杏仁酱真是优秀的面包伴侣！
10. 原来hart house如此的丰富！
11. 日本人怎么做炸鸡也好吃呀
12. 耶天气好好可以穿裙子啦
13. 我今天喝了一个红米肠汤 奶香奶香的 让我想到了一个豆子汤但是我想不起在哪里吃过的了
14. 在水煮肉片店吃到了番石榴味道水果糖 一秒回到老家
15. 香喷喷的自己我很喜欢
16. 谢谢你安睡裤我的生活离不开你
17. 天呐我想起来了那不是每次regina都会给我准备的豆子汤吗！！！虽然每次都问配方但我能做到一个步骤都记不住但问题不大
18. 谢谢你林子你很棒你热爱生活你总是好奇你喜欢体验你很勇敢给你一个大大拥抱
19. 大阪烧炒乌冬真好吃呀怎么这么好吃我很满足
20. 琼彬师姐回多伦多了我非常开心！可以一起吃喝玩乐
21. 是一直很正能量的阿远儿！我喜欢广东女孩子因为我喜欢阿远儿
22. 开心果冰激凌你很优秀但是可以不要那么甜
23. 谢谢我的网球搭子我迟到也总是没有说我
24. 以为没带电脑充电器但在包里找到充电器谢谢你充电器学习没有你就没有安全感！
25. 林子你好棒事情很多但是你把自己照顾得很好！
26. 今天下雪从gerstein穿过queens park回家路上太美了！怎么这条路秋冬都这么治愈！开始期待春夏
27. 天呐Kuan说Olli非常喜欢我北欧老师这么冷静的吗喜欢我但从来不笑 这难道就是小王子里狐狸的那句：看东西只有用心才能看得清楚，重要的东西用眼睛是看不见的
28. 恰到好处的倾听
29. 感谢押尾桑写作业有你我真的很安心
30. 今天我在看survival然后我随口感叹了一句每次不是office hout的时间我都会有很多疑问，但一到office hour就没有疑问..结果玫玫师姐接过我的notes问我哪里不懂就要给我讲..然后我就问了好多好多问题
31. 今天游泳有一个拄着拐杖的老奶奶非常敬畏
32. 今天早上出门走半路感觉到自己好像没带手机；觉得问题不是很大；以为会有一些FOMO但其实没有；作为一个很难戒断的人开始学习放下
33. 土豆泥好吃炖牛肉好吃
34. 今天走路上突然感觉好像马上要气胸了有点害怕还好是虚惊一场活着真不容易又苟活了一天！
35. 这世界不能没有音乐！多美的旋律呀！
36. 我好想念南山呀！
37. 今天中午吃饭我问我的饭搭子要不要什么时候去吃水煮肉片，我的饭搭子说今天中午少吃点，下午去吃！瞬间开心！
38. 当遇到一些不好的事情，首先接受告诉自己its ok not to be ok 然后告诉自己All is well 问题不是很大，并积极找到解决方案！！
39. 是听好多好多好多好多遍都不会腻的押尾桑！！！谢谢你的音乐非常治愈
40. 又是被琼彬师姐温暖的一天呀
41. 今天下楼大厅一直小狗狗🐶好可爱的跟着我好治愈
42. 今天也是被Olli温暖着的一天呀
43. 多关注自己的生活 世界上无聊的人就不要管他们了
44. 我喜欢我的东韵宝子 她在我眼里就很棒我会心疼她情绪不好看她情绪开心我也会很开心 谢谢她在我不开心以及不知道答案的时候也会在我身边
45. 不对人和事做过多评价让我觉得蛮开心的
46. 欣赏花骨朵非常治愈

## 四月
1. Lyna妹妹耐心地教我数学我感到很幸福
2. 我好想家呀我爱重庆
3. 我觉得周老师是一个很平静的人我希望我吐槽的戏剧的事情没有给他一些负能量
4. 嘻嘻玫玫师姐给我买了我喜欢的巧克力曲奇🍪惊喜
5. 芝士好好好好好好吃呀
6. 我喜欢的铅笔之前不好用了，我以为ta坏掉了，今天用ta又特别好用，我很开心
7. 哎呀我以为会议取消了结果没有老师说如果在calendar上就是没有取消好吧fine 确实也有道理但好在我及时看到了邮件…
8. 开心地⛸️好久没滑冰了下次应该是9月哈哈
9. 最近的🫐蓝莓有点好吃
10. 强迫症呀你乖一点再乖一点再乖一点点
11. 强迫症你乖乖的别怕别怕
12. 强迫症你很乖谢谢你
13. 吃到了好好闻的蜂蜜呀好幸福
14. 谢谢爸爸妈妈总会第一时间关心我！感恩
15. 最近的草莓也很好吃
16. 谢谢你蜂蜜水哈哈好好喝
17. 我今天打开我的concept proposal 和Olli的邮件往来我真的一下子开心滴笑出大声来 真的是被幸福暴击的时刻
18. 我想吃糯米的冰糖葫芦
19. 有风有雨是常态，风雨兼程是状态，风雨无阻是心态
20. 看妹妹笑得很开心问她是不是有什么好事情发生 妹妹说她每天都那么开心呀 我喜欢她的精神状态
21. 林子你很棒你非常棒你做得很好
22. 今天打🎾非常有感觉哈哈嗖嗖嗖的
23. 林子你超棒的
24. 我对今天的长游感到很满意
25. 樱花🌸开了好漂亮
26. 郁金香🌷开了好漂亮

## 五月
1. 我喜欢我的网球小姐妹今天随口说说结果她邀请我去她家游泳
2. 新唇膏是草莓味炫迈的味道几天后我终于意识到了
3. 如果我觉得没有被倾听我会难过一秒并觉得挺没有礼貌…然后告诉自己管好自己少点期待
4. 师姐给了我她的书真暖心
5. 师姐又非常暖心的给我
6. 我好想吃羊肉粉
7. 哈哈哈和周老师玩儿开心
8. 我想吃大面条酸辣粉炸酱面大猪肉大牛肉大羊肉
9. 师姐给我买了酸奶君好喝的
10. 林子你超棒的！
11. 妈呀我咋突然想吃胡辣汤
12. 我想我哥家旁边的小面条 得多好吃
13. 和Yan开心地吃饭饭然后聊天
14. 超喜欢小裙子
15. 谢谢押尾桑！
16. 想吃小鳝鱼

## 六月
1. 大池子真好游在水里就很开心自在
2. 灰色的歌单突然都可以听了
3. 夏天的空气闻起来好香
4. 林子你超棒的别着急一步一步来
5. 林子淡定你超棒加油
6. 今天嘟嘟送货的叔叔好治愈呀下楼拿快递他看我买得多不慌不忙地帮我打包很好让我能方便提 还指导我左手提啥右手提啥
7. 以为自己没带耳机但带了耳机🤗
8. 今天又是被爸妈和妹妹温暖的一天呐
9. 今天是被我的表弟温暖的一天哈哈哈
10. 今天又是被Olli温暖的一天 可以让我表达我真实的想法
11. 今天又是被玫玫师姐温暖的一天
12. appl音乐仿佛看过我的网易歌单有点被暖到
13. 今天也是被玫玫师姐暖到的一天
14. 一切的不开心被咖啡店员的一些small talk治愈感恩
15. 自己超棒的

## 七月

1. Olli看了我发给他的文章真的是惊喜
2. 林子你是很棒的加油加油
3. 今天去生煎店买吃的之后店员说需要等20分钟然后我就犹豫了一番因为有点赶时间但最后还是点了想要吃的然后坐在桌上看书等待我的好吃的没想到很快就给我做好了我很惊讶说这么快！店员可能看出来我开始的赶时间所以她说看我在这里等所以先给了我💗
4. 今天在哈特楼外边学习结果一个滑板少年他在做一个非常危险的动作每次都失败了我看着都疼每次他都大叫出来但他每次都立刻站起来然后又爬上楼梯重新开始有时候他好像也害怕因为他会偶尔不敢从楼梯下来但他就一直试一直试半小时后他的白t都脏了背后也全是汗粘住他的皮肤祝他好运
5. 林子你真的超棒加油
6. 好好喝的燕麦奶
7. 好吃的酸菜鱼但可以不要那么咸

## 八月

1. 妹妹长得快和我一样高了！和她呆在一起的每分每秒都很幸福
2. 舅舅烧的菜真好吃😋
3. 我爱火锅和串串 太好吃了
4. 和妹妹一起游泳
5. 谢谢妹妹我的旅游搭子 谢谢你永远不会生我的气 永远那么好带
6. 我和妹妹在阳台合作晒衣服 妹妹突然正经地说了一句 姐姐你真好 我说妹妹你也很好 家人就是这样没有条件的喜欢和爱
7. 出去玩儿一定要给妈妈打包一点礼物我妈老开心
8. 爱爸爸妈妈因为他们很爱我
9. 回家有一起打🎾的朋友好幸福呀

## 九月
1. 熟悉的t3 我跟妈妈说又是这个熟悉的老地方 这次它变得可爱了起来 一家人都没有哭鼻子
2. 每天走过queens park感受这里大树的变化 
3. 打完网球的我脑子特别清晰
4. clinical trial课学习到一些新的知识

## 十月
1. 网球进入下一个阶段有规律的进行上手发球的练习🎉
2. 喜欢十月的渐变色太美啦秋天不是告别的季节是收获的季节
3. 回来适应了一个月开始进入工作模式感到很满意
4. 一些chord change 更加流畅 棒棒滴
5. 又到了吃橙柚的季节喜欢：）
6. 今天一大早去AC打网球的路上经过back compus的枫树 太美了阳光洒在ta们身上
7. 好喜欢🍂秋天
8. 秋天真的好美好美好美
9. Lyna妹妹毕业了，2027年就是我！！！
10. 两只渴望知识的大眼睛瞪着我的老师
11. 室友给的冰激凌太好吃啦！
12. 我爱tuna wrap
13. 冰激凌给的快乐～
14. 突然一秒想喝维C 发现家里还有一片维C🥳

## 十一月
1. 下去取嘟嘟快递，送货大叔说嘟嘟到了多穿点衣服下来
2. 超好吃的sourdough
3. 偶尔允许自己吃冰激凌幸福感爆棚
4. 很好吃的青提
5. 今天有一点点想家
6. 今天我很棒因为我的右脚垫脚只能做到20个但是我还是坚持做完了一组 并且核心也坚持做了10个所以我应该是还挺棒的
7. 每次都要蹲下来插电脑充电器 最近才发现桌上有个小设计能坐着把电插上😅喜欢gerstein的理由➕1
8. 打网球超开心！！！
9. 林子超棒～来跟着自己哈！哈！哈！
10. 哈哈哈又是被师姐治愈的一瞬间～💕
11. 多伦多又开始了圣诞预热 圣诞氛围慢慢 好喜欢秋冬有好多节日可以过：）
12. 也许是心理作用但觉得自己的右脚提踵好像变得容易了一点点？👏 
13. 被好心人我的爸爸治愈的一天
14. 今天和舍友去吃congee女王
15. 好喜欢新雨伞的重量 刚好合适不多不少
16. 几天没吃到苹果了就得来点苹果
17. 这是需要多少黑科技才能做出这么优秀的🥐呀😋😋
18. 耳朵突然好了😀
19. 杏仁果好吃太好吃啦！！！
20. 突然想吃香蕉？
21. clinical trial课有点意思（可能因为不需要我去考试
22. 我妹告诉我她学校体测161cm 🤨（一定是测量工具有问题
23. 妹妹的新眼镜蛮好看的
24. 挫糯米团子好治愈，Q弹Q弹的，就是手上有点埋汰哈哈
25. 哇这个香水的味道特别好闻：）心情愉悦

## 十二月
1. 下雪太美啦❄️❄️
2. 超喜欢打球穿的小裙子～
3. 林子加油你是最棒的！
4. 今天本来身体有点不舒服结果打完网球身心愉悦～
5. 自己超棒的 把自己照顾很好～感恩的心❤️
6. 有时候非常感恩deadline这种东西
7. 在gerstein晒难得的阳光 学习变得很治愈～～感谢大自然
8. 今天阳光也很好～farm boy太好逛啦
9. 每天一颗苹果的快乐与满足感😋
10. 打网球真的也太快乐了吧～～～～～～～
11. sportcheck 嚼着口香糖的sale小哥帮我认真的选一条颜色合适的瑜伽带真是个好人
12. 今天网球场上遇到一老爷爷 给了我六颗penn
13. 今天上手发球有进步💃
14. 今天做了饼干&面包完美的圣诞节🎄
15. 今天🧗开始我有一点怕但是我竟然能够完成抱石 旁边的人看我好不容易终于send之后给我说well done：）
16. 暖心的Amy～～
17. 今天Philip广场滑冰的人很多，天气很好～
18. 今年冬天吃到最好吃的🫐
19. 终于把秋季开学在harthouse买的书看起来啦
20. 期末后RB common又安静了起来，坐下来就能想到自己夏天在这认真学习的样子
21. 自己动手换弦    
22. 包个饺子🥟 
23. 整理各种东西感到非常治愈



