---
title: "2025 Summary"
description: ""
tags: 
  - "annual"
---

## 一月

1. 在冰箱里翻翻找找我记忆中还有一颗的苹果，找了几下才找到了，没错今天我真的很需要这颗苹果
2. 提踵好像容易了一些
3. 玫玫师姐做的腊肠饭和腊排骨好吃
4. 神奇的山式
5. 有时候有点怂 师姐鼓励了我❤️
6. 又是啰啰嗦嗦地跟曹老师讲了好多废话的我 感谢他的耐心指导好像简单了一些
7. 家里人就像一棵大树一样给人安全感💕
8. 金桔🍊太好吃啦
9. 在饭盒里没见到我打包的水果以为带忘记掉了，结果在书包里找到了打包的水果
10. 师姐给我耐心地讲解东西
11. 打完球脑子清醒不少!
12. 谢谢押尾桑
13. 今天经过farm boy 去买超爱吃的sour dough 结账时随手➕了一块巧克力蛋糕😋 那是因为我今天去看了医生 有时候我吃甜食之前会想这东西不健康诸如此类  但今天吃它我一点点负罪感都没有 感恩活着真好

2024-03-14 re: 后来几次都没有在farm boy看到那一款巧克力蛋糕 所以当时一定有一股神秘力量让我看到那块超好吃蛋糕

## 二月

1. 一次一次又一次的被师姐温暖着～～
2. 是听无数遍也听不腻的押尾桑
3. 今天在书店看书读到一段话突然哭了… 因为想到我的脑子之前如何一点一点不受控制 有点trauma response…
4. 世界上怎么有这么好吃的苹果
5. 我的学生们暖心地过来对我表示了感谢
6. 今天下了好大的雪❄️我特别的兴奋和激动
7. 下雪天好漂亮
8. 好吃的🥬🥬🥬
9. 香香的味道很治愈
10. 今天去买了biscotti小饼干 我说我要一盒 但快下班了所以没有很多店员给了我所有的小饼干
11. 林子棒棒滴
12. 吃到了超超超好吃的巧克力棒
13. 无论好坏，全盘接受 thats ok 没事儿林子
14. 谢谢爸爸妈妈在我难过的时候会安慰我让我知道世界上有人一直关心着我
15. 我的一天：今天我觉得我挺棒的 因为早上出门考试电梯卡住了我想没事儿迟到一点没关系，我还去前台report了这件事情，前台小哥感谢了我；走到hs才想起考试地点不在上课的教室我想没事儿迟到一点没关系；考试的时候我的眼睛好像不能聚焦因为有点肿肿，我的脑袋也不知道在想什么，但我依然觉得没有关系，小小考试轻松拿下；下午要去tut, 我认真地准备了上课的内容，做一个helpful的人 下课时候我的学生说她试了pistachio 冰激凌然后说她很喜欢 她说因为第一节课我让他们自我介绍时每人说一个自己喜欢的ice cream flavor 然后我推荐了开心果 这个一天的highlight的点；下午快四点打开餐盒准备补充一点食物再去打球发现自己没有带餐具 我想没有关系我吃点水果也可以；打球的时候我好像挺专注的因为我可以接男生的球有时候我不觉得吃力；去更衣室的时候突然觉得空气有一点点变化好像一个脑袋的开关被打开



